"""News ticker headline templates — 100+ unique funny lines."""

TEMPLATES = {
    "trade": [
        "Sources say {team} traded {player} for 'culture' and a bag of picks",
        "BREAKING: {team} ships {player} out — league insiders cite 'vibes'",
        "{team} and {partner} completed a trade involving {player}. Nobody clapped.",
        "Trade alert: {player} is headed to {team}. Fantasy managers in shambles.",
        "{team} acquires {player} in a deal described as 'mutually confusing'",
        "League sources: {player} to {team}. Previous team sends a thumbs-up emoji.",
        "{team} trades for {player}; analytics department still loading the spreadsheet",
        "BLOCKBUSTER: {player} lands in {team}. Group chat erupts.",
        "{team} got {player} for 'future considerations' — the future is nervous",
        "Trade wire: {player} joins {team}. Old teammates unfollowed on Instagram.",
        "{team} swaps assets for {player}. Cap sheet needs a nap.",
        "Per sources, {player} is {team}'s problem now. Congratulations?",
    ],
    "signing": [
        "{player} signs with {team} for ${salary}M/yr, reportedly for the cafeteria fries",
        "{team} lands {player} on a ${salary}M deal — agent calls it 'market rate, emotionally'",
        "Free agency: {player} chooses {team} over literally sleeping on it",
        "{player} inks with {team}. Contract: ${salary}M. Happiness: pending.",
        "{team} signs {player} (${salary}M). Luxury tax accountants sweating.",
        "{player} picks {team} after exhaustive 48-hour deliberation",
        "Deal done: {player} to {team} for ${salary}M. Woj tweet incoming.",
        "{team} wins {player} bidding war with vibes and a mid-level exception",
        "{player} agrees to ${salary}M with {team}; cites 'good weather and Wi-Fi'",
        "Free agency splash: {team} adds {player} on ${salary}M/yr",
        "{player} tells {team} yes. Other suitors left on read.",
        "{team} closes on {player} (${salary}M). Champagne optional.",
    ],
    "rejection": [
        "{player} declined {team}'s ${salary}M offer, calling it 'a participation trophy contract'",
        "{player} told {team} to try again — with more zeros",
        "Sources: {player} rejected {team}'s offer and went to touch grass",
        "{player} passed on {team}. 'I know my worth,' said someone who definitely does.",
        "{team}'s ${salary}M pitch to {player} met with a polite 'nah'",
        "{player} ghosted {team}'s max offer. Respectfully.",
        "Report: {player} laughed, then declined {team}'s ${salary}M",
        "{team} whiffed on {player}. Cap space remains, dignity questionable.",
        "{player} chose elsewhere over {team}'s ${salary}M. Life goes on.",
        "Sources say {player} wanted more than {team} offered. Shocking.",
    ],
    "injury": [
        "{player} listed as OUT ({detail})",
        "{player} is day-to-day with a classic case of being too good",
        "Injury report: {player} — {detail}. Rival fans nod solemnly.",
        "{team}: {player} unavailable. Reason: {detail}",
        "{player} sidelined with {detail}. Fantasy owners refresh anxiously.",
        "Medical update: {player} ({detail}). Return timeline: TBD, vibes willing.",
        "{team} rules out {player} ({detail}). Backup plan: hope.",
        "{player} won't play tonight — {detail}. Coach says 'next man up.'",
    ],
    "game": [
        "{player} dropped {pts} on {opp}; defenders filed a complaint",
        "{player} went for {pts} vs {opp}. The box score needs a nap.",
        "Hot take: {player}'s {pts}-point night against {opp} was 'pretty good'",
        "{opp} couldn't stop {player} ({pts} PTS). Film study cancelled.",
        "{player} torched {opp} for {pts}. Security escorted the bucket out.",
        "Stat line alert: {player} — {pts} PTS vs {opp}. League notified.",
        "{player} put up {pts} on {opp}; opposing coach requested a do-over",
        "Vintage {player}: {pts} points vs {opp}. Somewhere, a podcast cried.",
        "{opp} had no answers for {player}'s {pts}-piece. Answers sold separately.",
        "{player} dropped {pts} on {opp}. Defenders union filing grievance.",
        "Box score hero: {player} ({pts} PTS) vs {opp}. Hat trick of buckets.",
        "{player} cooked {opp} for {pts}. Kitchen closed.",
    ],
    "upset": [
        "UPSET: {winner} ({w_score}) stuns {loser} ({l_score}). Brackets weep.",
        "{loser} lost to {winner}. Somewhere, a fan yelled at their TV.",
        "Shocker: {winner} beats {loser} {w_score}-{l_score}. Math is broken.",
        "{winner} shocks {loser} {w_score}-{l_score}. Vegas shrugs.",
        "Nobody saw this: {winner} over {loser} ({w_score}-{l_score})",
        "{loser} falls to {winner} {w_score}-{l_score}. Group chat meltdown.",
        "Upset alert: {winner} takes down {loser} {w_score}-{l_score}",
        "{winner} stuns {loser}. Bracketologists retire.",
        "Final: {winner} {w_score}, {loser} {l_score}. Chaos reigns.",
        "{loser} stunned by {winner} ({w_score}-{l_score}). Film at 11.",
    ],
    "rookie": [
        "Rookie watch: {player} ({team}) already looks like a steal at {overall} OVR",
        "League buzzing about {player} — {team}'s rookie is turning heads",
        "Scouts rave about {player}; {team} may have found a franchise piece",
        "Rookie sensation: {player} putting {team} on notice with elite flashes",
        "{player} is {team}'s rookie gem — analytics Twitter in meltdown mode",
        "Hot rookie alert: {player} ({team}) playing like a vet already",
        "{team} rookie {player} drawing comparisons to 'someone good, probably'",
        "Breakout rookie {player} has {team} fans refreshing the standings nightly",
        "Rookie radar: {player} at {overall} OVR and climbing for {team}",
        "{player} is the talk of the league — {team}'s draft pick paying off",
    ],
    "draft": [
        "{team} selects {player}; scout notes: 'he looks fast in 2K'",
        "With the pick, {team} takes {player}. Twitter is undefeated.",
        "{team} drafts {player}. Ceiling: sky. Floor: also sky, allegedly.",
        "Draft pick: {team} grabs {player}. Analysts say 'sure, why not'",
        "{team} tabs {player}. Mock drafts in shambles.",
        "On the clock: {team} picks {player}. Room goes quiet, then loud.",
        "{team} drafts {player}; mom cries, dad nods approvingly",
        "Draft night: {player} to {team}. Hometown hero or random guy? Yes.",
        "{team} selects {player}. Analytics guy nods, scout high-fives air.",
        "With the selection, {team} takes {player}. Future TBD.",
    ],
    "retirement": [
        "{player} hangs it up at {age}; league mourns, fantasy GMs rejoice",
        "{player} announces retirement. Highlights reel loading…",
        "End of an era: {player} retires. Someone please tell their agent.",
        "{player} calls it a career at {age}. Jersey retirement pending vibes check.",
        "Retirement: {player} ({age}). The league will miss the stories.",
        "{player} walks away at {age}. Sneaker deal survives.",
        "Farewell tour over: {player} officially retires at {age}",
        "{player} retires. Hall of Fame committee opens a fresh tab.",
    ],
    "pick_trade": [
        "{team} traded a pick for a {year} R{round} future pick. Time travel confirmed.",
        "Draft trade: {team} swaps picks for {year} R{round}. GM playing 4D chess (probably).",
        "{team} moves up/down for {year} R{round}. Fans debate for 72 hours.",
        "Pick swap: {team} acquires {year} R{round}. Future self thanks them.",
        "{team} trades draft capital for {year} R{round}. Spreadsheet enthusiasts rejoice.",
        "Draft board shake-up: {team} lands {year} R{round} via trade",
    ],
    "championship": [
        "CHAMPIONS: {team} win the NBA Finals — Larry O'Brien trophy secured",
        "{team} capture the title. Parade planning already underway.",
        "NBA Finals: {team} hoist the trophy. Confetti budget: unlimited.",
        "{team} are NBA champions. City officials brace for traffic.",
        "Title town: {team} win it all. Ring sizes TBD.",
        "{team} crowned champions. Champagne liability waiver signed.",
    ],
    "offcourt": [
        "{player} arrested outside arena 90 minutes before tipoff — charged with 'excessive drip'",
        "{player} on shopping spree: bought 400 tacos, cites 'bulking season'",
        "{player} cited for egging a rival fan's house; claims it was a 'passing drill'",
        "{player} missed shootaround after winning a Costco forklift license online",
        "{team} lists {player} as questionable — 'ate the entire Gatorade cooler'",
        "{player} detained before game for trying to pay parking in championship rings",
        "BREAKING: {player} bought every PS5 in a 50-mile radius 'for the locker room'",
        "{player} showed up to practice in a horse costume. Coach said 'sure'",
        "Police report: {player} caught sneaking 47 basketballs out of the arena gift shop",
        "{player} late to shootaround — was at Taco Bell ordering 'one of everything'",
        "{team}: {player} day-to-day after challenging a mascot to a dance-off and losing",
        "{player} arrested for public dunking on a residential hoop at 3 AM",
        "Sources: {player} spent $12,000 on sneakers, listed expense as 'medical'",
        "{player} missed flight to road game — thought the team bus was optional",
        "League investigating {player} for unauthorized use of confetti cannon in hotel lobby",
        "{player} cited for honking at refs in traffic. 'They know what they did.'",
        "{team} confirms {player} questionable — lost a bet and had to dye hair neon green",
        "{player} went viral for teaching a goldfish to shoot free throws. Still 68% FT.",
        "Report: {player} bought a pet alligator for the locker room. HR involved.",
        "{player} arrested before tipoff for attempting to trade teammates on fantasy mid-game",
        "{player} on 72-hour taco cleanse; strength coach 'concerned but intrigued'",
        "{team} lists {player} out — sprained ego after losing to a child in HORSE",
        "{player} spent off day at IKEA; team bus now full of flat-pack furniture",
        "Witnesses say {player} egged a billboard of a rival star. 'Artistic expression.'",
        "{player} detained for riding a shopping cart through mall at dangerous speeds",
        "Sources: {player} tried to bulk by eating only chicken nuggets for a month",
        "{player} missed curfew — was at a 24-hour Walmart 'getting essentials' (47 items)",
        "{team}: {player} questionable after winning an eating contest 2 hours before tip",
        "{player} arrested outside arena; told officers he was 'just stretching'",
        "BREAKING: {player} purchased 200 foam fingers, distributed them to entire block",
        "{player} listed as doubtful — lost phone in ball pit at kids' birthday party",
        "{team} investigating {player} for starting a podcast mid-timeout (unauthorized)",
        "{player} cited for parking in the commissioner's spot 'for the culture'",
        "Report: {player} went on shopping spree, bought team entire wardrobe from 2003",
        "{player} questionable — ankle rolled fleeing autograph seekers at mall food court",
    ],
    "ambient": [
        "League memo reminds players that the ball is for basketball, not juggling",
        "Sources say at least one GM still uses a flip phone. Respect.",
        "Breaking: water is wet, load management is controversial, sun rises in east",
        "Anonymous player polled: 94% would trade a first-round pick for uninterrupted sleep",
        "Commissioner denies rumor that the lottery is decided by a very large hamster wheel",
        "Stats dept confirms: most missed free throws blamed on 'rim unfairness'",
        "League office issues reminder: mascots are coworkers, not tackling dummies",
        "Report: average player spends 6 hours daily debating whether to post workout video",
        "Sources: {player} once asked if timeouts roll over to next season. They don't.",
        "{team} PR department wins award for 'most creative injury euphemisms'",
        "Hot take: {player} would dominate if games were decided by vibes alone",
        "League-wide poll: best road city for food? Results classified.",
    ],
}


def template_count():
    return sum(len(items) for items in TEMPLATES.values())


def all_categories():
    return list(TEMPLATES.keys())
